version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/itg_employee_manager
    depends_on:
      - mysqldb
      
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: itg_employee_manager

    volumes:
    - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      
      
networks:
  springapimysql-net: