spring.application.name=employee_manager
server.error.whitelabel.enabled=false

# JSP views configurations
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# MySQL server connection configurations
spring.datasource.url=jdbc:mysql://localhost:3306/itg_employee_manager
spring.datasource.username=root
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.show-sql=true

#Spring mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${sender_email_username}
spring.mail.password=${sender_email_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties[mail.smtp.connectiontimeout]=5000
spring.mail.properties[mail.smtp.timeout]=3000
spring.mail.properties[mail.smtp.writetimeout]=5000


